#!/usr/bin/env bash

# Spark Master Settings
export SPARK_MASTER_HOST=${SPARK_MASTER_HOST:-$(hostname)}
export SPARK_MASTER_PORT=${SPARK_MASTER_PORT:-7077}
export SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT:-8080}

# Spark Worker Settings
export SPARK_WORKER_CORES=${SPARK_WORKER_CORES:-4}
export SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY:-6G}
export SPARK_WORKER_INSTANCES=${SPARK_WORKER_INSTANCES:-2}
export SPARK_WORKER_DIR=${SPARK_WORKER_DIR:-/tmp/spark-worker}
export SPARK_WORKER_WEBUI_PORT=${SPARK_WORKER_WEBUI_PORT:-8081}

# Executor Settings
export SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY:-6G}
export SPARK_EXECUTOR_INSTANCES=${SPARK_EXECUTOR_INSTANCES:-2}
export SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES:-5}

# Driver Memory
export SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY:-2G}

# Local IP
export SPARK_LOCAL_IP=${SPARK_LOCAL_IP:-$(hostname -i)}

# Python path
export PYSPARK_PYTHON=${PYSPARK_PYTHON:-python3}
export PYSPARK_DRIVER_PYTHON=${PYSPARK_DRIVER_PYTHON:-python3}
